

export const metadata = {
    title: "Our -Products",
    description: "Generated by create next app",
};

export default function ProductsLayout({ children }) {
    return (
        <>
            {children}
        </>
    )
}
